language: python
python:
  - "2.6"
  - "2.7"

install: pip install -r requirements.txt --use-mirrors

services:
  - elasticsearch

before_script:
  - sed -ie 's/\/opt\/Brownian\//\/home\/travis\/build\/grigorescu\/Brownian\//' Brownian/settings.py
  - curl -s -XPOST localhost:9200/_bulk --data-binary @tests/data.json
  - DJANGO_SETTINGS_MODULE="Brownian.settings" python ./manage.py syncdb --noinput

script: DJANGO_SETTINGS_MODULE="Brownian.settings" nosetests